apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-deployment
  labels:
    app: review
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-pod
  template:
    metadata:
      labels:
        app: review-pod
    spec:
      containers:
        - name: review-container
          image: localhost:5000/review/latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-deployment
  labels:
    app: recommendation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendation-pod
  template:
    metadata:
      labels:
        app: recommendation-pod
    spec:
      containers:
        - name: recommendation-container
          image: localhost:5000/recommendation/latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
  labels:
    app: product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-pod
  template:
    metadata:
      labels:
        app: product-pod
    spec:
      containers:
        - name: product-container
          image: localhost:5000/product/latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: composite-pod
spec:
  containers:
    - name: composite-container
      image: localhost:5000/product-composite/latest
      imagePullPolicy: Never
      ports:
        - containerPort: 80
          name: composite-port
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  ports:
    - name: app-port
      protocol: TCP
      port: 80
      targetPort: composite-port

